### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by apurbapathak** [pulkitpareek18/netflix#3]
I test your script, it's down.

**Comment by pulkitpareek18** [comment]
It's fine now.

**Comment by apurbapathak** [comment]
This site can’t be reached
**embed.smashystream.com** took too long to respond.

**Comment by pulkitpareek18** [comment]
It may be because of your ISP or any adblock extension, on my end it's perfectly working. 
![image](https://github.com/pulkitpareek18/netflix/assets/84959590/15282d4e-cd97-4e72-8beb-0260e6deb96d)
